# Generated by Django 3.2 on 2021-05-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_number', models.PositiveSmallIntegerField()),
                ('drown_number', models.PositiveSmallIntegerField()),
                ('amount', models.FloatField()),
                ('win', models.BooleanField()),
                ('money', models.FloatField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bet',
                'verbose_name_plural': 'Bets history',
                'db_table': 'bets_history',
            },
        ),
        migrations.CreateModel(
            name='CasinoPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fb_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('user_discord_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fb_name', models.CharField(blank=True, max_length=75, null=True)),
                ('discord_name', models.CharField(blank=True, max_length=75, null=True)),
                ('money', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('take_daily', models.BooleanField(default=0)),
                ('daily_strike', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'db_table': 'casino_players',
            },
        ),
        migrations.CreateModel(
            name='UsersTotalMoneyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_money', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Total money history data',
                'verbose_name_plural': 'Total money history data',
                'db_table': 'users_total_money_history',
            },
        ),
        migrations.CreateModel(
            name='TwentyFourHoursMoneyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_twenty_four_hours_history_data', to='casino.casinoplayers')),
            ],
            options={
                'verbose_name': 'Money daily history data',
                'verbose_name_plural': 'Money daily history',
                'db_table': 'twenty_four_hours_money_history',
            },
        ),
        migrations.CreateModel(
            name='MoneyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_money_history', to='casino.casinoplayers')),
            ],
            options={
                'verbose_name': 'Money history data',
                'verbose_name_plural': 'Money history',
                'db_table': 'money_history',
            },
        ),
        migrations.CreateModel(
            name='JackpotsResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_jackpots_results', to='casino.casinoplayers')),
            ],
            options={
                'verbose_name': 'Jackpot result',
                'verbose_name_plural': 'Jackpots Results',
                'db_table': 'jackpots_results',
            },
        ),
        migrations.CreateModel(
            name='Jackpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets', models.PositiveIntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_jackpot', to='casino.casinoplayers')),
            ],
            options={
                'verbose_name': 'Jackpot',
                'verbose_name_plural': 'Jackpot',
                'db_table': 'jackpot',
            },
        ),
    ]
